[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tritonparse"
version = "0.0.5"
dependencies = [
    "triton",
]

[project.optional-dependencies]
test = [
    "coverage>=7.0.0",
]

[tool.setuptools.packages.find]
include = ["tritonparse*"]

[tool.ruff]
line-length = 88

[tool.black]
line-length = 88
target-version = ["py310"]

[project.urls]
"Homepage" = "https://github.com/pytorch-labs/tritonparse"
